import { ActionRowBuilder, ButtonBuilder, ButtonStyle, ChannelType, MessageFlags, PermissionFlagsBits, type Interaction } from "discord.js";
import type { SessionService } from "../application/session-service.js";
import type { SettlementService, SettlementSnapshotDto } from "../application/settlement-service.js";
import type { ReminderService } from "../application/reminder-service.js";
import type { ReminderWorker } from "../reminders/worker.js";
import { ApplicationError } from "../application/errors.js";
import type { SessionDto } from "../application/types.js";
import { makeCustomId, parseCustomId } from "./custom-id.js";
import { ReminderDraftStore, type ReminderDraft } from "./reminder-drafts.js";
import { balancesView, previewView, reminderDraftView, reminderFieldsModal, reminderView, settlementView, transferActionView } from "./settlement-views.js";

const actions = new Set(["preview","ppage","finalize","settlement","balances","transfer","paid","unpaid","invalidate","invconfirm","close","closeconfirm","reminder","remedit","remchannel","remfields","remsave","remcancel","remstop","remsend"]);
const mentions = { parse: [] as never[] };
const privateReply = { flags: MessageFlags.Ephemeral as const, allowedMentions: mentions };
const drafts = new ReminderDraftStore();
type Services = { sessions: SessionService; settlements: SettlementService; reminders: ReminderService; worker: ReminderWorker };

export async function handleSettlementInteraction(services: Services, interaction: Interaction): Promise<boolean> {
  if (!interaction.isMessageComponent() && !interaction.isModalSubmit()) return false;
  if (!interaction.customId.startsWith("wk1:")) return false;
  const parsed = parseCustomId(interaction.customId);
  if (!parsed || !actions.has(parsed.action)) return false;
  if (!interaction.inGuild() || !interaction.guildId) { await interaction.reply({...privateReply,content:"サーバー内で実行してください。"}); return true; }
  const {action,sessionId,revision,arg}=parsed; const actor=interaction.user.id;
  if (!sessionId) { await interaction.reply({...privateReply,content:"セッションを確認できません。"}); return true; }
  const scope={guildDiscordId:interaction.guildId,actorDiscordUserId:actor,sessionId};
  const fail=async(content:string)=>{if(interaction.deferred||interaction.replied) await interaction.followUp({...privateReply,content}); else await interaction.reply({...privateReply,content});};
  const render=async(s:SessionDto,payload:object)=>{if(interaction.deferred||interaction.replied) await interaction.editReply({...payload,allowedMentions:mentions}); else if(interaction.isMessageComponent()) await interaction.update({...payload,allowedMentions:mentions});};
  const userError=(e:unknown)=>e instanceof ApplicationError && e.code==="REVISION_CONFLICT"?"セッションが更新されています。画面を開き直してください。":e instanceof ApplicationError && e.code==="UNPAID_TRANSFERS"?"未払いの送金があります。":e instanceof ApplicationError && e.code==="NO_UNPAID_TRANSFERS"?"未払いの送金はありません。":e instanceof ApplicationError && e.code==="REMINDER_RATE_LIMITED"?"通知は現在送信できません。時間をおいて再試行してください。":e instanceof ApplicationError && e.code==="INVALID_INPUT"?"入力形式または値を確認してください。":"操作を完了できませんでした。対象と権限を確認してください。";
  let s:SessionDto;
  try { s=services.sessions.getSession(scope); } catch(e) { await fail(userError(e)); return true; }
  if(s.revision!==revision){await fail("セッションが更新されています。画面を開き直してください。");return true;}
  const current=():SettlementSnapshotDto=>services.settlements.getCurrent(scope);
  const checkSettlement=(sid:string)=>{const st=current();if(st.id.replaceAll("-","")!==sid)throw new ApplicationError("SETTLEMENT_NOT_CURRENT","Stale settlement.");return st;};
  try {
    if((action==="preview"||action==="ppage") && interaction.isButton()) { if(s.status!=="ACTIVE") throw new Error(); const p=services.settlements.preview(scope); const page=action==="ppage"?Number.parseInt(arg,36):0; await interaction.update({...previewView(s,p,actor,Number.isSafeInteger(page)?page:0),allowedMentions:mentions}); return true; }
    if(action==="finalize" && interaction.isButton()) { if(s.creatorDiscordUserId!==actor) throw new Error(); const result=services.settlements.finalize(scope,{expectedRevision:revision}); const updated=services.sessions.getSession(scope); const text=result.becameAllPaid?"精算を確定しました。送金はありません。すべて支払い済みです。":"精算を確定しました。"; await interaction.update({...settlementView(updated,result.settlement,0,actor),content:text,allowedMentions:mentions}); return true; }
    if(action==="settlement" && interaction.isButton()) { const st=s.status==="CLOSED"?services.settlements.list(scope)[0]:current(); if(!st)throw new Error(); const [hex,pageText]=arg.split("_"); if(hex && st.id.replaceAll("-","")!==hex)throw new Error(); const p=pageText?Number.parseInt(pageText,36):0; await interaction.update({...settlementView(s,st,Number.isSafeInteger(p)?p:0,actor),allowedMentions:mentions}); return true; }
    if(action==="balances" && interaction.isButton()) { const [hex,pageText]=arg.split("_"); const st=checkSettlement(hex??""); const page=pageText?Number.parseInt(pageText,36):0; await interaction.update({...balancesView(s,st,Number.isSafeInteger(page)?page:0),allowedMentions:mentions}); return true; }
    if(action==="transfer" && interaction.isStringSelectMenu()) { const st=checkSettlement(arg.split("_")[0]!); const transfer=st.transfers.find(t=>t.id.replaceAll("-","")===interaction.values[0]); if(!transfer)throw new Error(); const member=(mid:string)=>s.members.find(m=>m.id===mid)?.discordUserId; if(actor!==s.creatorDiscordUserId&&actor!==member(transfer.fromMemberId)&&actor!==member(transfer.toMemberId))throw new Error(); await interaction.update({...transferActionView(s,st,transfer.id.replaceAll("-","")),allowedMentions:mentions}); return true; }
    if((action==="paid"||action==="unpaid")&&interaction.isButton()){const st=current(); const result=services.settlements.setTransferStatus(scope,st.id,normalizeUuid(arg),action==="paid"?"PAID":"UNPAID",{expectedRevision:revision}); const updated=services.sessions.getSession(scope); await interaction.update({...settlementView(updated,result.settlement,0,actor),...(result.becameAllPaid?{content:"すべての送金が支払済みになりました。作成者はセッションを完了できます。"}:{}),allowedMentions:mentions});return true;}
    if((action==="invalidate"||action==="close")&&interaction.isButton()){const st=checkSettlement(arg);if(actor!==s.creatorDiscordUserId)throw new Error();const confirm=action==="invalidate"?"invconfirm":"closeconfirm";const label=action==="invalidate"?"精算を解除":"完了する";await interaction.reply({...privateReply,content:action==="invalidate"?"精算を解除して編集可能に戻しますか？":"すべて支払い済みです。セッションを完了しますか？",components:[new ActionRowBuilder<ButtonBuilder>().addComponents(new ButtonBuilder().setCustomId(makeCustomId(confirm,s.id,s.revision,st.id.replaceAll("-",""))).setLabel(label).setStyle(ButtonStyle.Danger))]});return true;}
    if((action==="invconfirm"||action==="closeconfirm")&&interaction.isButton()){if(actor!==s.creatorDiscordUserId)throw new Error();const st=checkSettlement(arg);if(action==="invconfirm"){services.settlements.invalidate(scope,st.id,{expectedRevision:revision});const updated=services.sessions.getSession(scope);await interaction.update({content:"精算を解除しました。",...await import("./session-views.js").then(m=>m.sessionDetailView(updated,actor)),allowedMentions:mentions});}else{const result=services.settlements.close(scope,st.id,{expectedRevision:revision});const updated=services.sessions.getSession(scope);await interaction.update({...settlementView(updated,result.settlement,0,actor),content:"セッションを完了しました。",allowedMentions:mentions});}return true;}
    if(action==="reminder"&&interaction.isButton()){const st=current();const setting=services.reminders.get(scope);await interaction.update({...reminderView(s,st,setting,actor),allowedMentions:mentions});return true;}
    if(action==="remedit"&&interaction.isButton()){const st=checkSettlement(arg);if(actor!==s.creatorDiscordUserId)throw new Error();const old=services.reminders.get(scope);const d=drafts.create({owner:actor,guild:interaction.guildId,session:s.id,revision,settlementId:st.id,channelId:old?.channelId??"",firstReminderText:"",intervalHoursText:String((old?.intervalSeconds??86400)/3600)});await interaction.update({...reminderDraftView(s,d),allowedMentions:mentions});return true;}
    if(action==="remchannel"&&interaction.isChannelSelectMenu()){const [token,gen]=arg.split("_");const st=current();const d=drafts.get(token??"",actor,interaction.guildId,s.id,revision,st.id);if(!d||d.generation.toString(36)!==gen)throw new Error();d.channelId=interaction.values[0]??"";d.generation++;await interaction.update({...reminderDraftView(s,d),allowedMentions:mentions});return true;}
    if(action==="remfields"&&interaction.isButton()){const [token,gen]=arg.split("_");const st=current();const d=drafts.get(token??"",actor,interaction.guildId,s.id,revision,st.id);if(!d||d.generation.toString(36)!==gen||actor!==s.creatorDiscordUserId)throw new Error();await interaction.showModal(reminderFieldsModal(makeCustomId("remfields",s.id,revision,`${d.token}_${d.generation.toString(36)}`),d));return true;}
    if(action==="remfields"&&interaction.isModalSubmit()){const [token,gen]=arg.split("_");const st=current();const d=drafts.get(token??"",actor,interaction.guildId,s.id,revision,st.id);if(!d||d.generation.toString(36)!==gen||actor!==s.creatorDiscordUserId)throw new Error();d.firstReminderText=interaction.fields.getTextInputValue("first").trim();d.intervalHoursText=interaction.fields.getTextInputValue("hours").trim();d.generation++;await interaction.deferReply(privateReply);await render(s,reminderDraftView(s,d));return true;}
    if(action==="remsave"&&interaction.isButton()){const [token,gen]=arg.split("_");const st=current();const d=drafts.get(token??"",actor,interaction.guildId,s.id,revision,st.id);if(!d||d.generation.toString(36)!==gen||actor!==s.creatorDiscordUserId)throw new Error();if(!d.channelId)throw new Error();const channel=await interaction.guild!.channels.fetch(d.channelId);const botMember=interaction.guild!.members.me;if(!channel||channel.guildId!==interaction.guildId||(channel.type!==ChannelType.GuildText&&channel.type!==ChannelType.GuildAnnouncement)||!channel.isTextBased()||!botMember||!channel.permissionsFor(botMember)?.has([PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages]))throw new Error();const updated=services.sessions.getSession(scope);const latest=services.settlements.getCurrent(scope);const valid=drafts.get(token??"",actor,interaction.guildId,updated.id,revision,latest.id);if(updated.revision!==revision||latest.id!==st.id||!valid||valid.generation.toString(36)!==gen)throw new Error();const first=parseJst(d.firstReminderText);const hours=/^[1-9]\d*$/.test(d.intervalHoursText)?Number(d.intervalHoursText):NaN;if(!Number.isSafeInteger(hours)||hours>8760)throw new ApplicationError("INVALID_INPUT","Enter an integer interval between 1 and 8760 hours.");services.reminders.configure(scope,{channelId:d.channelId,...(first===undefined?{}:{firstReminderAt:first}),intervalSeconds:hours*3600});drafts.delete(d.token);await interaction.update({...reminderView(updated,latest,services.reminders.get(scope),actor),content:"リマインド設定を保存しました。",allowedMentions:mentions});return true;}
    if(action==="remcancel"&&interaction.isButton()){const [token,generation]=arg.split("_");const st=current();const draft=drafts.get(token??"",actor,interaction.guildId,s.id,revision,st.id);if(!draft||draft.generation.toString(36)!==generation||actor!==s.creatorDiscordUserId)throw new Error();drafts.delete(draft.token);await interaction.update({...reminderView(s,st,services.reminders.get(scope),actor),allowedMentions:mentions});return true;}
    if(action==="remstop"&&interaction.isButton()){checkSettlement(arg);if(actor!==s.creatorDiscordUserId)throw new Error();services.reminders.stop(scope);await interaction.update({...reminderView(s,current(),services.reminders.get(scope),actor),content:"自動通知を停止しました。",allowedMentions:mentions});return true;}
    if(action==="remsend"&&interaction.isButton()){checkSettlement(arg);if(actor!==s.creatorDiscordUserId)throw new Error();const latest=services.sessions.getSession(scope);const st=current();if(latest.revision!==revision||st.id.replaceAll("-","")!==arg)throw new Error();const claim=services.reminders.claimManual(scope);services.worker.queueManual(claim);await interaction.update({...reminderView(s,st,services.reminders.get(scope),actor),content:"手動通知を受け付けました。送信処理はバックグラウンドで行われます。",allowedMentions:mentions});return true;}
  } catch(e){await fail(userError(e));return true;}
  return true;
}

function normalizeUuid(v:string):string{if(!/^[0-9a-f]{32}$/i.test(v))throw new Error();return `${v.slice(0,8)}-${v.slice(8,12)}-${v.slice(12,16)}-${v.slice(16,20)}-${v.slice(20)}`;}
function parseJst(value:string):number|undefined{if(!value)return undefined;const m=/^(\d{4})-(\d{2})-(\d{2}) (\d{2}):(\d{2})$/.exec(value);if(!m)throw new ApplicationError("INVALID_INPUT","Enter a future JST time as YYYY-MM-DD HH:mm.");const [year,month,day,hour,minute]=m.slice(1).map(Number);const utc=Date.UTC(year!,month!-1,day!,hour!-9,minute!);const date=new Date(utc);if(date.getUTCFullYear()!==year||date.getUTCMonth()!==month!-1||date.getUTCDate()!==day||date.getUTCHours()!==hour!-9||date.getUTCMinutes()!==minute)throw new ApplicationError("INVALID_INPUT","Enter a valid calendar time.");if(utc<=Date.now())throw new ApplicationError("INVALID_INPUT","Reminder time must be in the future.");return utc;}
